boards/_base/realtek-ambz-4mb-980k.json

The ld files are named rlx8711B-symbol-v02-img2_xip1_4M_980k_cpp.ld and rlx8711B-symbol-v02-img2_xip2_4M_980k_cpp.ld but they are referenced as rlx8711B-symbol-v02-img2_xip1_4M_cpp.ld

[realtek-ambz] Fix 4M/980k linker script name

---

arduino/beken-72xx/cores/arduino/wiring_analog.c

Some of my BK7231N RGBWW bulbs were occasionally flickering when they turned on/off with libretuya-esphome.  This was more noticeable at higher PWM frequencies.  I discovered that when the pwm dutycycle value is set to 0 then the output goes high.  This doesn't seem to affect my BK7231T based bulbs.

[beken-72xx] Fix for flicker when PWM lights turn on/off on bk7231n

---

cores/beken-72xx/base/api/lt_sleep.c

Manufacturer docs: https://docs-bekencorp-com.translate.goog/sdk_3.0.x/bk7238/html/developer-guide/power_save/sleep_test.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=hu&_x_tr_pto=wapp
Discussion: https://github.com/libretiny-eu/libretiny-esphome/pull/11

[beken-72xx] Fix GPIO deep sleep wakeup edge

---

cores/common/arduino/libraries/api/Serial/Serial.cpp

This PR changes the SerialClass::available() return value to 0 if no data is available on the referenced UART port. 
Issues:
#153
#155

[libs] Fix SerialClass available() return value 

---

docs/resources/tuya-pin-config.md

Based on description from tuya website (links provided in #218) I have filled in some of the missing information. The description was for bluetooth devices, but the keys I described seem to be more or less universal.

[docs] Add more UPK key descriptions

---

cores/beken-72xx/arduino/src/wiring.c
cores/beken-72xx/arduino/src/wiring_analog.c
cores/beken-72xx/arduino/src/wiring_data.h

This seems to resolve issues that occured when pwm was stopped on N-chips.
Instead of stopping, we should do pause (ie. "unit disable"), when duty cycle is 0.
I couldn't make it work using "CMD_PWM_UNIT_DISABLE" and then "CMD_PWM_UNIT_ENABLE", as "disabling" seems to do some additional cleanup for some reason. Although it seems to be working fine with "CMD_PWM_INIT_PARAM" instead of "enabling".
I decided it will be easier to track the state as an enum, so that now it's clear when we should (re)start and/or pause or do full stop.

[beken-72xx] Pause PWM instead of stopping, track PWM state

---

docs/projects/esphome.md

The docs about using docker  compose for libre tuya had an error. When setting what image to use in compose you dont have to put docker pull, just the image you are going to use

[docs] Update docker compose image name

---

cores/beken-72xx/arduino/libraries/WiFi/WiFi.cpp
cores/beken-72xx/arduino/libraries/WiFi/WiFiPrivate.h
cores/beken-72xx/arduino/libraries/WiFi/WiFiSTA.cpp

bk72xx - Allow connecting to a specific BSSID via `bk_wlan_start_sta_adv` which is bssid-aware, instead of `bk_wlan_start_sta` which is not, and falling back to `bk_wlan_start_sta` when one is not present (fast_connect).

[beken-72xx] Allow connecting to specific BSSID if provided

---

cores/beken-72xx/arduino/src/wiring_analog.c

One of the users reported issue esphome/issues#5201 with ADC on BK7231N, so I took a look at the code and found something that could be related. I don't own any N device with ADC, so cannot really test this. But I have checked my T devices with this fix and the ADC still works there.

[beken-72xx] Improve ddev ADC support

---

cores/beken-72xx/arduino/libraries/WiFi/WiFiScan.cpp
cores/common/arduino/libraries/api/WiFi/WiFi.h
cores/common/arduino/libraries/api/WiFi/WiFiScan.cpp
cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp

This method might return a dynamically allocated buffer which should be freed by the caller (the example code does it). Not doing this results in memory leaks.

[beken-72xx] Free list returned by wlan_sta_scan_result()

---

cores/common/arduino/libraries/common/Update/Update.cpp

When the MCU is started with OTA1 image and you try to update the firmware, the OTA process fails:
```
[D][ota:320]: OTA in progress: 48.8%
[D][ota:320]: OTA in progress: 65.1%
[D][ota:320]: OTA in progress: 81.5%
E [  57890.676] OTA: Error: MD5 Check Failed
E [  57890.680] OTA: - written: 1380864 of 1380864
E [  57890.688] OTA: - buf: size=2199023255552, left=1153652920625948496
E [  57890.691] OTA: - ctx: seq=4294967295, part=(null)
E [  57890.699] OTA: - buf: seq=2696/2697, addr=689920, len=252
[W][ota:336]: Error ending OTA!, error_code: 132
```
Turns out that `lt_ota_write()` modifies the data ("binpatch" to update memory addresses for OTA2) and therefore MD5Update has to be called _before_ writing the data.

[libs] Fix MD5 calculation during OTA update

---

cores/beken-72xx/base/api/lt_sleep.c

per https://github.com/libretiny-eu/libretiny/issues/230
Tested on several BK7231N devices with ESPHome 2024.1.0-dev.

[beken-72xx] Fix duration rollover in deep sleep

---

cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp

```
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 80:A0:36:A7:F7:1F
interface 0 is initialized
interface 1 is initialized
Initializing WIFI ...
WIFI initialized
[D][wifi:459]: Starting scan...
RTL8195A[HAL]: Hard Fault Error!!!!
RTL8195A[HAL]: R0 = 0x1b9
```
As explained by @kuba2k2: "It seems that scanAlloc() returns the amount of allocated items, then the Realtek code tries to assign to the last item. The index in [] is wrong though, it tries to assign to one item past the last one."
Fixes #257

[realtek-ambz] Fix crash after WiFi scan

---

cores/common/arduino/libraries/common/mDNS/LwIPmDNS.cpp
cores/common/arduino/libraries/common/mDNS/mDNS.cpp
cores/common/arduino/libraries/common/mDNS/mDNS.h

strcpy() always adds null-terminator at the end.
The original code allocated one byte less than what is needed, so it was overwriting _something_. Could've been important or not :)
Found this while debugging #248, but I don't know if it fixes it or not. In my local tests on ubuntu I was not able to reproduce the behavior described in #248. But if it's memory related, then it's bound to behave differently on x86 + linux. Worth checking if it helped.

[libs] Fix mDNS string memory corruption, print error on record add failure

---

cores/beken-72xx/base/api/lt_sleep.c
cores/beken-72xx/base/fixups/sys_ctrl.c
cores/beken-72xx/base/sdk_extern.h
cores/common/base/api/lt_sleep.c
cores/common/base/api/lt_sleep.h

According to guide `gpio_stay_*_map` are specifically there to prevent pulling pins to a specific level and let them float during deep sleep.
https://docs.bekencorp.com/sdk_3.0.x/bk7238/build/en/latest/developer-guide/power_save/sleep_test.html
This allows any external low-power circuitry to change a pin level, as required, to trigger the wake up.
This requires changes in BDK and was implemented via fixup. Also, exposed `gpio_stay_lo_map` parameter via `lt_deep_sleep_keep_floating_gpio` to manage this configuration for pins in range P0-P31.

[beken-72xx] Allow setting deep sleep wake-up pins as floating

---

cores/realtek-ambz2/base/config/lwipopts.h

fixes compiling/linking errors in esphome. I was using esphome 2024.5.4

[realtek-ambz2] Fix C linkage for sys_now() in lwipopts

---

cores/beken-72xx/arduino/src/wiring_irq.c

The CHANGE implementation used the wrong logic (using gpioMode instead of irqMode to switch the interrupt edge).
It also changes the edge after calling the isr instead of before (to avoid signal changes while servicing the isr, though that would be bad anyway).
It also sets the initial edge based on the current level of the pin.

[beken-72xx] Fix CHANGE interrupt logic

---

boards/variants/wbr3.h

This is necessary; `WBR3` is not in the `feature/i2c-spi` branch, and this fixes about `feature/realtek-update` without the concerns of `feature/i2c-spi` -- perhaps I misunderstand the relevant comment, however.
https://github.com/libretiny-eu/libretiny/issues/44#issuecomment-1792656300
https://github.com/baltpeter/libretiny/commit/a92983a608836a380adfeb76eaa968f1dcabf27b

[realtek-ambz2] Define PIN_SERIAL0_RX/TX for wbr3

---

boards/_base/pcb/afw121t.json
boards/_base/realtek-ambz-1mb-468k.json
boards/afw121t.json
boards/templates/99iot-21p.json
boards/variants/afw121t.c
boards/variants/afw121t.h

[boards] Add RTL8710BX AFW121T board

---

builder/family/realtek-ambz2.py

Do not include partition table & bootloader in device schemes (consistent with other supported families). Fix partition table & bootloader marked as `SINGLE` instead of `DUAL_1/2` in the flasher scheme, thus skipped during flashing using `ltchiptool`.

[realtek-ambz2] Fix partition table & bootloader flashing via UART

---

cores/beken-72xx/arduino/libraries/Serial/SerialPrivate.h
cores/common/arduino/libraries/api/Serial/Serial.h
cores/common/arduino/libraries/api/SoftwareSerial/SoftwareSerial.h
cores/common/base/lt_config.h
cores/realtek-amb/arduino/libraries/SoftwareSerial/SoftwareSerial.cpp
cores/realtek-ambz/arduino/libraries/Serial/SerialPrivate.h
cores/realtek-ambz2/arduino/libraries/Serial/SerialPrivate.h

Increase RX buffer from 64 bytes to 256 bytes (ESPHome UART bus component default). Other sizes can easily be defined in ESPHome YAML e.g. like this:
```
bk72xx:
board: cbu
framework:
options:
LT_SERIAL_BUFFER_SIZE: 512
```
Preparatory work for https://github.com/esphome/issues/issues/6240. ESPHome could change `LT_SERIAL_BUFFER_SIZE` whenever `rx_buffer_size:` is changed.
Also covertly increases the send buffer for SoftwareSerial, but that should have no side effects.

[common] Make Serial RX buffer size configurable, increase default to 256 bytes

---

boards/_base/ic/ln882hk.json
boards/variants/generic-ln882hki.c
boards/variants/ln-02.c
boards/variants/wl2s.c
cores/lightning-ln882h/arduino/src/wiring_irq.c
docs/status/supported.md

- all GPIOS can generate interrupts
- added calls to NVIC_SetPriority/NVIC_EnableIRQ/NVIC_DisableIRQ
I couldn't test detachInterrupt (where I added a call to NVIC_DisableIRQ) but attachInterruptParam now works.

[lightning-ln882h] Fix GPIO interrupt support

---

boards/_base/pcb/wb02a-test.json
boards/_base/pcb/wb02a.json
boards/variants/wb02a.c
boards/variants/wb02a.h
boards/wb02a.json

another LN882H variant I found in a smart switch

[boards] Add WB02A board
